version: 2.1

orbs:
  node: circleci/node@5
  browser-tools: circleci/browser-tools@1.4.8

jobs:

  test-browser:
    docker:
      - image: cimg/node:18.20-browsers
    environment:
      - CHROME_BIN: /usr/bin/google-chrome
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build with browser tests
          command: npm run build
      - run:
          name: Run tests
          command: npm run test:browser --passWithNoTests

  test-node:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build with Node tests
          command: npm run build
      - run:
          name: Run tests
          command: npm run test:node --passWithNoTests

  build:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build package
          command: npm run build
      - run:
          name: Bundle dev version of a package
          command: npm run bundle-dev
  lint:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint


workflows:
  build-and-test:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test-node:
          requires:
            - build
      - test-browser:
          requires:
            - build